name: vit_logger
description: A simple logging package with customization in mind.
version: 2.1.1
repository: https://github.com/TimeLord2010/vit_logger.git

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
